nav:
- Coding:
  - C:
    - C Note （前八章）: .\Coding\C\C Note （前八章）.md
  - Matlab:
    - Notes of Matlab: .\Coding\Matlab\Notes of Matlab.md
- index: .\index.md
- Lesson at School:
  - 大一春夏:
    - 信电导:
      - 1-3230103034-李昕: .\Lesson at School\大一春夏\信电导\1-3230103034-李昕.md
      - 3-3230103034-李昕: .\Lesson at School\大一春夏\信电导\3-3230103034-李昕.md
    - 口译:
      - 口译作业: .\Lesson at School\大一春夏\口译\口译作业.md
      - 欢迎辞 祝酒辞: .\Lesson at School\大一春夏\口译\欢迎辞 祝酒辞.md
    - 大物(I):
      - 20240411 大物课: .\Lesson at School\大一春夏\大物(I)\20240411 大物课.md
    - 奇奇怪怪的通识课:
      - 无线电网络: .\Lesson at School\大一春夏\奇奇怪怪的通识课\无线电网络.md
      - 经济法-备考: .\Lesson at School\大一春夏\奇奇怪怪的通识课\经济法-备考.md
      - 经济法: .\Lesson at School\大一春夏\奇奇怪怪的通识课\经济法.md
      - 经济法第七讲: .\Lesson at School\大一春夏\奇奇怪怪的通识课\经济法第七讲.md
      - 雕版印刷与刻本文化: .\Lesson at School\大一春夏\奇奇怪怪的通识课\雕版印刷与刻本文化.md
    - 工训:
      - 工程训练: .\Lesson at School\大一春夏\工训\工程训练.md
    - 概统:
      - 概统第2章知识点汇总: .\Lesson at School\大一春夏\概统\概统第2章知识点汇总.md
- 支教备课录:
  - 2024 春夏 青海黄南:
    - 二项分布: .\支教备课录\2024 春夏 青海黄南\二项分布.md
    - 前言、数学学习方法分享: .\支教备课录\2024 春夏 青海黄南\前言、数学学习方法分享.md
    - 第一讲、二项式定理: .\支教备课录\2024 春夏 青海黄南\第一讲、二项式定理.md
    - 第二讲 条件概率: .\支教备课录\2024 春夏 青海黄南\第二讲 条件概率.md
    - 第四讲: .\支教备课录\2024 春夏 青海黄南\第四讲.md
    - 第四讲课后习题: .\支教备课录\2024 春夏 青海黄南\第四讲课后习题.md
  - 支教面试准备:
    - 暑期支教准备: .\支教备课录\支教面试准备\暑期支教准备.md
    - 讲稿-面试: .\支教备课录\支教面试准备\讲稿-面试.md
- 更新日志:
  - Log: .\更新日志\Log.md
- 考核方式汇总: .\考核方式汇总.md
- 随便写写:
  - Diary:
    - April:
      - '2024-04-16': .\随便写写\Diary\April\2024-04-16.md
      - '2024-04-19': .\随便写写\Diary\April\2024-04-19.md
      - '2024-04-21': .\随便写写\Diary\April\2024-04-21.md
      - '2024-04-22': .\随便写写\Diary\April\2024-04-22.md
      - '2024-04-25': .\随便写写\Diary\April\2024-04-25.md
      - '2024-04-29': .\随便写写\Diary\April\2024-04-29.md
      - '2024-04-30': .\随便写写\Diary\April\2024-04-30.md
      - 20240414 日记: .\随便写写\Diary\April\20240414 日记.md
      - '20240416': .\随便写写\Diary\April\20240416.md
    - May:
      - '2024-05-02': .\随便写写\Diary\May\2024-05-02.md
      - '2024-05-04': .\随便写写\Diary\May\2024-05-04.md
      - '2024-05-05': .\随便写写\Diary\May\2024-05-05.md
      - '2024-05-11': .\随便写写\Diary\May\2024-05-11.md
      - '2024-05-12': .\随便写写\Diary\May\2024-05-12.md
      - '2024-05-14': .\随便写写\Diary\May\2024-05-14.md
    - 乱记:
      - Askbox: .\随便写写\Diary\乱记\Askbox.md
      - Note-间歇性日记: .\随便写写\Diary\乱记\Note-间歇性日记.md
  - Essay:
    - About IAI: .\随便写写\Essay\About IAI.md
    - 《用随机梯度下降来优化人生》 --李沐: .\随便写写\Essay\《用随机梯度下降来优化人生》 --李沐.md
    - 【ACEE】一些迟到的心得记录和碎碎念: .\随便写写\Essay\【ACEE】一些迟到的心得记录和碎碎念.md
    - 转专业路上的碎碎念: .\随便写写\Essay\转专业路上的碎碎念.md
  - Plans:
    - Plans: .\随便写写\Plans\Plans.md
