version: '3'

services:
    ethereum:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: private_chain
        ports:
            - "8545:8545"
        env_file:
            - .env
        volumes:
            - ./data:/data
            - ./logs:/var/log/regeth
    
    faucet:
        image: chainflag/eth-faucet:1.1.0
        restart: unless-stopped
        container_name: private_faucet
        ports:
            - "58080:8080"
        links:
            - ethereum
        env_file:
            - .env
        command: -wallet.provider ${WEB3_PROVIDER_URI} -wallet.privkey ${ALLOC_ADDRESS_PRIVATE_KEY} -faucet.minutes 1
        depends_on:
            - ethereum
